// Code to pass JavaScript code to the browser
void jsHeader() {
  client << "<script language=\"javascript\">\n";
  client << "  $( document ).ready(function() {\n";
  client << "    drawTable();\n";
  client << "  });\n";
  client << "</script>\n";
}
void jsMain() {
client << "    <script language=\"javascript\">\n";
client << "        var tIndex = 0;\n";
client << "        function solveGrid(){\n";
client << "            $(\".btn\").prop(\"disabled\", true);\n";
client << "            var pChars = \"\";\n";
client << "            for(var r = 0; r < 9; r++){\n";
client << "                for(var c = 0; c < 9; c++){\n";
client << "                    var ic = $(\"#r\"+r+\"c\"+c).prop(\"disabled\", true);\n";
client << "                    var cp = ic.val();\n";
client << "                    if(cp >= \"1\" && cp <= \"9\") {\n";
client << "                        pChars += cp;\n";
client << "                    } else {\n";
client << "                        pChars += \".\"\n";
client << "                        ic.css({\"background-color\": \"CornflowerBlue\"}).addClass(\"blank\");\n";
client << "                    }\n";
client << "                }\n";
client << "            }\n";
client << "            $(\"#pprompt\").html(\"Solving, please wait...\");\n";
client << "            $.get(\"ajax/\", pChars, readResult)\n";
client << "        }\n";
client << "        function readResult(m) {\n";
//client << "            alert(m);\n";
client << "            var ret = jQuery.parseJSON(m);\n";
client << "            if(ret.error){\n";
client << "                $(\"#pprompt\").html(ret.solved); // displays the error message\n";
client << "            } else {\n";
client << "                setTable(ret.solved);\n";
client << "                var res = \"Solved in \";\n";
client << "                if(ret.msecs >= 1000){\n";
client << "                    res += ret.msecs / 1000 + \" seconds<br />\";\n";
client << "                } else {res += ret.msecs + \" milliseconds<br />\";}\n";
client << "                if(ret.tot > 1){\n";
client << "                    res += \"using \" + ret.tot + \" attempts with a maximum search depth of \" + ret.max;\n";
client << "                } else {\n";
client << "                    res += \"at the first attempt.\"\n";
client << "                }\n";
client << "                $(\"#pprompt\").html(res);\n";
client << "            }\n";
client << "            $(\".blank\").animate({\"background-color\": \"white\"}, 3000).removeClass(\"blank\");\n";
client << "            $(\".cell\").prop(\"disabled\", false);\n";
client << "            $(\".btn\").prop(\"disabled\", false);\n";
client << "        }\n";
client << "        function setTable(values) {\n";
client << "            var charPos = 0\n";
client << "            for(var r = 0; r < 9; r++){\n";
client << "                for(var c = 0; c < 9; c++){\n";
client << "                    var cp = values.charAt(charPos++);\n";
client << "                    if(cp < \"1\" || cp > \"9\"){cp = \"\";}\n";
client << "                    $(\"#r\"+r+\"c\"+c).val(cp);\n";
client << "                }\n";
client << "            }\n";
client << "            tIndex < 3 ? tIndex++ : tIndex=0;\n";
client << "        }\n";
client << "        function clearTable() {\n";
client << "            $(\".cell\").val(\"\");\n";
client << "        }\n";
client << "        function drawTable() {\n";
client << "            var dt = $(\"#dvTable\");\n";
client << "            var t1 = $(\"<table>\").css({\"background-color\": \"blue\", \"margin\": \"auto\"});\n";
client << "            for(var r = 0; r < 3; r++) {\n";
client << "                var tr = $(\"<tr>\");\n";
client << "                for (var c = 0; c < 3; c++) {\n";
client << "                    var td = $(\"<td>\");\n";
client << "                    var t2 = $(\"<table>\").css(\"background-color\", \"CornflowerBlue\");\n";
client << "                    for(var ir = 0; ir < 3; ir++){\n";
client << "                        var itr = $(\"<tr>\")\n";
client << "                        for(var ic = 0; ic < 3; ic++){\n";
client << "                            var id = \"r\" + (r * 3 + ir) + \"c\" + (c * 3 + ic);\n";
client << "                            itr.append($(\"<td>\").append($(\"<input>\")\n";
client << "                            .attr({type: \"text\", maxlength: \"1\", size: \"1\", id: id}).css({height: \"2em\"})\n";
client << "                            .addClass(\"cell\").val(\"\")))\n";
client << "                        }\n";
client << "                        t2.append(itr);\n";
client << "                    }\n";
client << "                    tr.append(td.append(t2));\n";
client << "                }\n";
client << "                t1.append(tr);\n";
client << "            }\n";
client << "            dt.html(t1).css({\"display\": \"flex\", \"align-items\": \"center\"});\n";
client << "        }\n";
client << "        var testers = [\n";
client << "        \".2.4.6..76..2.753...5.8.1.2.5..4.8.9.6159...34.28.3..1216...49.......31.9.8...2..\",\n";
client << "        \"....6.......4.367...5..7....9....4..1.....9.3.32....58.1.52..97.5...98......862..\",\n";
client << "        \"4.....8.5.3..........7......2.....6.....8.4......1.......6.3.7.5..2.....1.4......\",\n";
client << "        \"......52..8.4......3...9...5.1...6..2..7........3.....6...1..........7.4.......3.\"]\n";
client << "    </script>\n";
}
